data:
  frequency: 5m
  timestep: 5m
  format: zarr
  radar_imputer:
    default: "none"
    0:
      - lwe_precipitation_rate  
  meps_imputer:
    default: "none"
    0:
      - tp
  qc:
    nordic_radar:
      qc_var: qc_flags
      method: decode_bits
      num_bits: 11
      invalid_bit_indices: [0, 4, 5, 6, 8, 10]
  datasets:
    meps:
      dataset:  ${system.input.meps}
      forcing: ${system.input.meps.select}
      prognostic: []
      diagnostic: []
      processors:
        normalizer:
          _target_: anemoi.models.preprocessing.normalizer.InputNormalizer
          config:
            default: "mean-std"
        meps_imputer:
          _target_: anemoi.models.preprocessing.imputer.ConstantImputer
          config: ${data.meps_imputer}
    nordic_radar:
      dataset:  ${system.input.nordic_radar}
      forcing: [ qc_flags ]
      diagnostic: []
      processors:
        normalizer:
          _target_: anemoi.models.preprocessing.normalizer.InputNormalizer
          config:
            default: "std"
            none: "qc_flags"
        radar_imputer:
          _target_: anemoi.models.preprocessing.imputer.ConstantImputer
          config: ${data.radar_imputer}
  num_features: null

dataloader:
  meps: ${system.input.meps}
  nordic_radar: ${system.input.nordic_radar}
  model_run_info: null
  validation_rollout: 10
  prefetch_factor: 2
  pin_memory: true
  read_group_size: ${system.hardware.num_gpus_per_model}
  num_workers:
    training: 1
    validation: 1
    test: 1
  batch_size:
    training: 1
    validation: 1
    test: 1
  debug:
    timing_data_enabled: true
    timing_data_every: 10
    timing_step_enabled: true
    timing_step_every: 10
    timing_model_enabled: true
    timing_model_every: 10
    timing_rank0_only: true
    # options: dense | auto_sparse | sparse
    time_index_mode: auto_sparse
  training:
    datasets:
      meps:
        dataset_config:
          dataset: ${dataloader.meps}
          frequency: ${data.frequency}
        start: 2020-11-13
        end: 2024-11-13
      nordic_radar:
        dataset_config:
          dataset: ${dataloader.nordic_radar}
          frequency: ${data.frequency}
        start: 2020-11-13
        end: 2024-11-13
  validation:
    datasets:
      meps:
        dataset_config:
          dataset: ${dataloader.meps}
          frequency:  ${data.frequency}
        start: 2024-11-14
        end: 2024-11-15
      nordic_radar:
        dataset_config:
          dataset: ${dataloader.nordic_radar}
          frequency:  ${data.frequency}
        start: 2024-11-14
        end: 2024-11-15
  test:
    datasets:
      meps:
        dataset_config:
          dataset: ${dataloader.meps}
          frequency:  ${data.frequency}
        start: 2025-04-13
        end: 2025-04-13
      nordic_radar:
        dataset_config:
          dataset: ${dataloader.nordic_radar}
          frequency:  ${data.frequency}
        start: 2024-11-14
        end: 2025-04-13
  limit_batches:
    training: 6500
    validation: null
    test: null

diagnostics:
  benchmark_profiler:
    memory:
      enabled: False
      steps: 5
      warmup: 2
      extra_plots: False
      trace_rank0_only: False
    time:
      enabled: True
      verbose: False
    speed:
      enabled: True
    system:
      enabled: False
    model_summary:
      enabled: False
    snapshot:
      enabled: False
      steps: 4
      warmup: 0
  plot:
    parameters: [ lwe_precipitation_rate ]
    sample_idx: 0
    precip_and_related_fields: [ lwe_precipitation_rate ]
    asynchronous: false 
    datashader: true 
    frequency: # Frequency of the plotting
      batch: 6500
      epoch: 1
    colormaps:
      precip:
        _target_: anemoi.training.utils.custom_colormaps.MatplotlibColormapClevels
        clevels: ["#ffffff", "#04e9e7", "#019ff4", "#0300f4", "#02fd02", "#01c501", "#008e00", "#fdf802", "#e5bc00", "#fd9500", "#fd0000", "#d40000", "#bc0000", "#f800fd"]
        variables: ${diagnostics.plot.precip_and_related_fields}
    datasets_to_plot: ["nordic_radar"]
    callbacks:
      - _target_: anemoi.training.diagnostics.callbacks.plot.MultiStepPlot
        dataset_names: ["nordic_radar"] 
        sample_idx: ${diagnostics.plot.sample_idx}
        per_sample : 6
        parameters: ${diagnostics.plot.parameters}
        output_steps: ${training.multistep_output}
        every_n_batches: ${diagnostics.plot.frequency.batch}
        video: true
        animation_interval: 650
        video_fps: 4
        frame_dpi: 200
        accumulation_levels_plot: [0, 0.05, 0.1, 0.25, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 7, 100] # in mm
        precip_and_related_fields: ${diagnostics.plot.precip_and_related_fields}
        colormaps: ${diagnostics.plot.colormaps}
  callbacks: []
  debug:
    anomaly_detection: false
  enable_checkpointing: false
  checkpoint:
    every_n_minutes: {save_frequency: 0, num_models_saved: 0}
    every_n_epochs: {save_frequency: 1, num_models_saved: -1}
    every_n_train_steps: {save_frequency: 0, num_models_saved: 0}
  log:
    wandb:
      enabled: false
      offline: false
      log_model: false
      project: Anemoi
      entity: null
      gradients: false
      parameters: false
    tensorboard:
      enabled: false
    mlflow:
      enabled: False
      _target_: anemoi.training.diagnostics.mlflow.logger.AnemoiMLflowLogger
      offline: False
      authentication: False
      tracking_uri: https://mlflow.ecmwf.int
      experiment_name: 'test-radar-debug'
      project_name: 'Anemoi'
      system: False
      terminal: True
      run_name: null
      on_resume_create_child: True
      expand_hyperparams: 
        - config
      http_max_retries: 35
      max_params_length: 2000
      save_dir: ${system.output.logs.mlflow}
    interval: 1
  enable_progress_bar: true
  print_memory_summary: true

system:
  output:
    root: /scratch/project_465002688/omiralle/bris_multisource/
    logs:
      root: logs
      wandb: wandb
      mlflow: mlflow
      tensorboard: tensorboard
    checkpoints:
      root: checkpoint
      every_n_epochs: anemoi-by_epoch-epoch_{epoch:03d}-step_{step:06d}
      every_n_train_steps: anemoi-by_step-epoch_{epoch:03d}-step_{step:06d}
      every_n_minutes: anemoi-by_time-epoch_{epoch:03d}-step_{step:06d}
    plots: plots
    profiler: profiler
  input:
    truncation: null
    truncation_inv: null
    warm_start: null
    meps: 
      dataset: /scratch/project_465002688/datasets/aifs-meps-2.5km-2020-2025-6h-v7.zarr
      fill_missing_dates: "interpolate"
      select:
        # - 10fg
        # - 10si
        # - 10u
        # - 10v
        - 2d
        # - 2t
        - tp
        # - cbh
        # - cos_julian_day
        # - cos_latitude
        # - cos_local_time
        # - cos_longitude
        # - fog
        # - hcc
        # - insolation
        - lcc
        - lsm
        - mcc
        - msl
        # - skt
        # - sp
        # - ssrd
        # - strd
        # - tcc
        # - tcw
        # - vis
        # - t_50
        # - u_50
        # - v_50
        # - w_50
        - z
        # - z_50
      interpolate_frequency: 5m
    nordic_radar: 
      dataset: /scratch/project_465002688/datasets/nordic-radar-2020-2025-1km-5m.zarr
      fill_missing_dates: "interpolate"
    graph: ${system.output.root}graph/nordic_interp.pt
  hardware:
    accelerator: auto
    num_gpus_per_node: 8
    num_gpus_per_ensemble: 8
    num_nodes: ${oc.decode:${oc.env:SLURM_NNODES}}
    num_gpus_per_model: 8

graph:
  overwrite: false
  hidden: hidden
  nodes:
    meps:
      node_builder:
        _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
        dataset: ${dataloader.meps}
      attributes: ${graph.attributes.nodes}
    nordic_radar:
      node_builder:
        _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
        dataset: ${dataloader.nordic_radar}
      attributes: ${graph.attributes.nodes}
    hidden:
      node_builder:
        _target_: anemoi.graphs.nodes.RegionalTriMeshNodes
        reference_node_name: nordic_radar
        spacing_km: 8
        margin_km: 10
  edges:
    - source_name: meps
      target_name: ${graph.hidden}
      edge_builders:
      - _target_: anemoi.graphs.edges.KNNEdges
        num_nearest_neighbours: 8
        source_mask_attr_name: null
        target_mask_attr_name: null
      attributes: ${graph.attributes.edges}
    - source_name: nordic_radar
      target_name: ${graph.hidden}
      edge_builders:
      - _target_: anemoi.graphs.edges.KNNEdges
        num_nearest_neighbours: 8
        source_mask_attr_name: null
        target_mask_attr_name: null
      attributes: ${graph.attributes.edges}
    - source_name: ${graph.hidden}
      target_name: ${graph.hidden}
      edge_builders:
        - _target_: anemoi.graphs.edges.TriangulationEdges
      attributes: ${graph.attributes.edges}
    - source_name: ${graph.hidden}
      target_name: nordic_radar
      edge_builders:
        - _target_: anemoi.graphs.edges.KNNEdges
          num_nearest_neighbours: 4
          source_mask_attr_name: null
          target_mask_attr_name: null
      attributes: ${graph.attributes.edges}
  attributes:
    nodes:
      area_weight:
        _target_: anemoi.graphs.nodes.attributes.UniformWeights
        norm: unit-max
    edges:
      edge_length:
        _target_: anemoi.graphs.edges.attributes.EdgeLength
        norm: unit-std
      edge_dirs:
        _target_: anemoi.graphs.edges.attributes.EdgeDirection
        norm: unit-std
  post_processors:
  - _target_: anemoi.graphs.processors.RemoveUnconnectedNodes
    nodes_name: nordic_radar
model:
  num_channels: 96
  condition_on_residual: False
  output_mask:
    _target_: anemoi.training.utils.masks.NoOutputMask
  cpu_offload: False
  keep_batch_sharded: false
  model:
    _target_: anemoi.models.models.Nowcaster
  layer_kernels:
    LayerNorm:
      _target_: torch.nn.LayerNorm
    Linear:
      _target_: torch.nn.Linear
    Activation:
      _target_: torch.nn.GELU
    QueryNorm:
      _target_: anemoi.models.layers.normalization.AutocastLayerNorm
      bias: False
    KeyNorm:
      _target_: anemoi.models.layers.normalization.AutocastLayerNorm
      bias: False
  processor:
    _target_: anemoi.models.layers.processor.GraphTransformerProcessor
    trainable_size: 0
    sub_graph_edge_attributes: ${model.attributes.edges}
    num_layers: 12
    num_chunks: 2
    mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
    num_heads: 8 # GraphTransformer or Transformer only
    qk_norm: True # Transformer and GraphTransformer only
    cpu_offload: ${model.cpu_offload}
    gradient_checkpointing: True
    graph_attention_backend: "triton"
    edge_pre_mlp: False
    layer_kernels:
      LayerNorm:
        _target_: anemoi.models.layers.normalization.AutocastLayerNorm
        bias: False
      Linear:
        _target_: torch.nn.Linear
      Activation:
        _target_: torch.nn.GELU
      QueryNorm:
        _target_: anemoi.models.layers.normalization.AutocastLayerNorm
        bias: False
      KeyNorm:
        _target_: anemoi.models.layers.normalization.AutocastLayerNorm
        bias: False
  encoder:
    _target_: anemoi.models.layers.mapper.GraphTransformerForwardMapper
    trainable_size: 0
    sub_graph_edge_attributes: ${model.attributes.edges}
    num_chunks: 4
    mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
    num_heads: 8 # GraphTransformer or Transformer only
    qk_norm: False
    cpu_offload: ${model.cpu_offload}
    gradient_checkpointing: True
    layer_kernels: ${model.layer_kernels}
    shard_strategy: "edges"
    graph_attention_backend: "triton"
    edge_pre_mlp: False
  decoder_graph_selection:
    strategy: dataset
    provider_datasets:
      meps: meps
      nordic_radar: nordic_radar
  decoder_conditioning:
    method: film
    key: cond            
  decoder:
    _target_: anemoi.models.layers.mapper.GraphTransformerBackwardMapper
    trainable_size: 0
    sub_graph_edge_attributes: ${model.attributes.edges}
    num_chunks: 4
    mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
    num_heads: 8 # GraphTransformer or Transformer only
    initialise_data_extractor_zero: False
    qk_norm: False
    cpu_offload: ${model.cpu_offload}
    gradient_checkpointing: True
    layer_kernels: ${model.layer_kernels}
    shard_strategy: "edges"
    graph_attention_backend: "triton"
    edge_pre_mlp: False
  residual:
    _target_: anemoi.models.layers.residual.SkipConnection # options: SkipConnection, TruncatedConnection
    step: -1 # use the latest step as skip connection
  trainable_parameters:
    meps: 0
    hidden: 0
    nordic_radar: 0
  attributes:
    edges:
      - edge_length
      - edge_dirs
    nodes: []
  # Torch compile configuration
  # A list of modules present in the model, which will be compiled
  # You can optionally pass options to torch.compile with the 'options' key
  #
  # Below is an explanation of some common parameters to torch.compile
  # For a full list of possible parameters, consult the documenation for torch compile
  #       https://docs.pytorch.org/docs/stable/generated/torch.compile.html
  #
  # dynamic (bool): When True, it will try to avoid recompilation by generating
  #       as general a kernel as possible. But the performance of the general
  #       kernel might be worse. When False, it will generate a specific
  #       kernel for each input shape (until the configurable recompile
  #       limit has been hit), leading to possibly better performance but
  #       more recompilations
  # mode (str): Different compilation modes, allowing you to trade off
  #       compilation time versus potential performance. See the
  #       torch.compile documentation for list of possible modes
  # fullgraph (bool): When True, torch.compile will error when it hits a
  #       section of code it can't compile. When False, it will fallback to
  #       non-compiled ("eager") execution for those lines.
  # options (dict): a dict of further options which can be passed to torch.compile
  compile:
    - module: anemoi.models.layers.conv.GraphTransformerConv
    - module: anemoi.models.layers.normalization.ConditionalLayerNorm
  bounding:
    - _target_: anemoi.models.layers.bounding.ReluBounding
      variables: [lwe_precipitation_rate]

training:
  multistep_output: 4
  update_ds_stats_on_ckpt_load:
    states: False 
    tendencies: True 
  known_future_variables: 
    datasets:
      meps: ${system.input.meps.select}
      
  scalers:
    datasets:
      meps:
        general_variable:
          _target_: anemoi.training.losses.scalers.GeneralVariableLossScaler
          weights: {default: 1}
        nan_mask_weights:
          _target_: anemoi.training.losses.scalers.NaNMaskScaler
        node_weights:
          _target_: anemoi.training.losses.scalers.GraphNodeAttributeScaler
          nodes_name: meps
          nodes_attribute_name: area_weight
          norm: unit-sum
      nordic_radar:
        general_variable:
          _target_: anemoi.training.losses.scalers.GeneralVariableLossScaler
          weights: {default: 1}
        nan_mask_weights:
          _target_: anemoi.training.losses.scalers.NaNMaskScaler
        node_weights:
          _target_: anemoi.training.losses.scalers.GraphNodeAttributeScaler
          nodes_name: nordic_radar
          nodes_attribute_name: area_weight
          norm: unit-sum
  variable_groups:
    datasets:
      meps:
        default: sfc
        pl: []
      nordic_radar:
        default: sfc
        pl: []
  run_id: null
  fork_run_id: null
  load_weights_only: false
  transfer_learning: false
  deterministic: false
  precision: bf16-mixed
  recompile_limit: 32
  accum_grad_batches: 1
  num_sanity_val_steps: 1
  gradient_clip: {val: 1000.0, algorithm: value}
  swa: {enabled: false, lr: 0.0001}
  optimizer:
    _target_: torch.optim.AdamW
    betas: [0.9, 0.95]
  model_task: anemoi.training.train.tasks.GraphNowcaster
  ensemble_size_per_device: 1
  strategy:
    _target_: anemoi.training.distributed.strategy.DDPGroupStrategy
    num_gpus_per_model: ${system.hardware.num_gpus_per_model}
    read_group_size: ${dataloader.read_group_size}
  training_loss:
    datasets:
      nordic_radar:
        _target_: anemoi.training.losses.combined.CombinedLoss
        scalers: ["node_weights", "nan_mask_weights"]
        loss_weights: [0.6, 0.4]
        losses:
          - _target_: anemoi.training.losses.spectral.LogSpectralDistance
            transform: "fft2d"
            x_dim: 2134
            y_dim: 1694
            ignore_nans: false
            apply_filter: true
            nodes_slice: [0, null]
          - _target_: anemoi.training.losses.spectral.FourierCorrelationLoss
            transform: "fft2d"
            x_dim: 2134
            y_dim: 1694
            ignore_nans: false
            apply_filter: true
            nodes_slice: [0, null]
  validation_metrics:
    datasets:
      nordic_radar:
        mse:
          _target_: anemoi.training.losses.spectral.LogSpectralDistance
          x_dim: 2134 
          y_dim: 1694
          transform: "fft2d"
          scalers: ["node_weights"]
          ignore_nans: True
  loss_gradient_scaling: false
  max_epochs: 20
  max_steps: 200000
  lr:
    warmup: 1000
    iterations: ${training.max_steps}
    rate: 6.25e-5
    min: 3.0e-8
  multistep_input: 6
  explicit_times:
    input: [0, 24]
    target: [1, 3, 6, 12]
  metrics: 
    datasets:
      nordic_radar: []
      meps: []
  submodules_to_freeze: []
  rollout:
    start: 1
    epoch_increment: 0
    max: 1
config_validation: false
